server:
  host: localhost
  port: 8080
  requestTimeoutSeconds: 60
database:
  dbname: "sport_tracker"
  dbuser: "postgres"
  dbpassword: "sql"
  dbconnection: "192.168.0.5"
  dbsslmode: "disable"
jwtSigningKey: "<pass jwt signing key>"